---
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

**Scover** includes a function for formatting the input data quickly from a 
SingleCellExperiment (`sce`) object. Make sure to store the cell type annotation 
in `colData(sce)$cell_type1`. This guide is for scRNA-seq
data, and it will use sequences of 500 bp upstream and 500bp downstream of the 
TSS for each gene. 
For a more detailed guide including other options, see the [other guide](https://scover.readthedocs.io/en/latest/how_to_prepare_scover_input_using_scRNA_seq.html) in 
this repository. It is recommended to use the other option as you can get a better understanding of what
pool size will be the best for your dataset. 

To run the script, you need to give the following command-line arguments:
```
-p POOL_SIZE (number of cells in each pool)
-d DATASET.RDS (SCE R object)
-o OUTPUT_PREFIX 
-c ORGANISM (mouse (default)/human)
```

You can pass the output directory as well using `-w OUTPUT_DIR`. Make sure that
the directory already exists. The default output directory is the current 
directory.

Example command to run:
```
Rscript create_dataset.R -p 100 -d dataset.RDS -o TEST_DATASET -c mouse -w output_directory
```

This will create three files in `output_directory`:

1. `TEST_DATASET_pool100.tsv.gz`
2. `TEST_DATASET_pool100_colData.tsv`
3. `TEST_DATASET_pool100_cells_in_pools.tsv`

You want to pass file 1) to the `--data` argument of scover, and file 2) to the 
`--celldata` of scover. For more information on how to run scover, see the main
readme file in the root of this repository. 
